package com.vr.domain;
// Generated 2017-8-13 11:29:14 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "vr")
public class Comments implements java.io.Serializable {

	private Integer id;
	private Integer postsId;
	private Integer userId;
	private String contents;
	private String date;

	public Comments() {
	}

	public Comments(Integer postsId, Integer userId, String contents, String date) {
		this.postsId = postsId;
		this.userId = userId;
		this.contents = contents;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "posts_id")
	public Integer getPostsId() {
		return this.postsId;
	}

	public void setPostsId(Integer postsId) {
		this.postsId = postsId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "contents")
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
