package com.vr.domain;
// Generated 2017-8-13 11:29:14 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts", catalog = "vr")
public class Posts implements java.io.Serializable {

	private Integer id;
	private String title;
	private String contents;
	private String date;
	private Integer posterId;
	private String posterName;
	private Integer totalComments;

	public Posts() {
	}

	public Posts(String title, String contents, String date, Integer posterId, String posterName, Integer totalComments) {
		this.title = title;
		this.contents = contents;
		this.date = date;
		this.posterId = posterId;
		this.posterName = posterName;
		this.totalComments = totalComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "contents")
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "poster_id")
	public Integer getPosterId() {
		return this.posterId;
	}

	public void setPosterId(Integer posterId) {
		this.posterId = posterId;
	}
	
	@Column(name = "poster_name")
	public String getPosterName() {
		return this.posterName;
	}

	public void setPosterName(String posterName) {
		this.posterName = posterName;
	}
	
	@Column(name = "total_comments")
	public Integer getTotalComments() {
		return this.totalComments;
	}

	public void setTotalComments(Integer totalComments) {
		this.totalComments = totalComments;
	}

}
